### ISSUE TITLE
MIT License issue

### ISSUE THREAD

**Issue by epiccakeking** [Aadit-Ambadkar/AoPS-Enhanced-F#1]
Please fix your License file to include my name. The MIT License requires that the copyright notice be included in all copies or substantial portions of the software, and thus the line "Copyright (c) 2021 epiccakeking" must be preserved in derivatives.

Also, could you indicate that this is not an official "Version 7" of AoPS Enhanced?

**Comment by Aadit-Ambadkar** [comment]
Yup, done! Sorry about that, I just used the default License and forgot to edit it.
